# NumPy

### NumPy Library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

#### Importing numpy

In [1]:
import numpy as np
#if not installed, install it using 'pip install numpy' in your terminal and then import it

#### In Numpy, number of dimensions of the array is called rank of the array.

#### Creating arrays

In [2]:
a=np.array([1,2,3]) #rank 1 array
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
# 'ndim' for number of dimensions of an array
print('The dimension of array is: ',a.ndim)

The dimension of array is:  1


In [4]:
# rank 2 array
b=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(b)

numpy.ndarray

In [6]:
print('The dimension of array is: ',b.ndim)

The dimension of array is:  2


In [7]:
# rank 3 array
a = np.array([[[10.,20],[30,40]],
              [[40,50],[60,70]],
              [[80,90],[100,110]]])
a

array([[[ 10.,  20.],
        [ 30.,  40.]],

       [[ 40.,  50.],
        [ 60.,  70.]],

       [[ 80.,  90.],
        [100., 110.]]])

In [8]:
type(a)

numpy.ndarray

In [9]:
print('The dimension of array is: ',a.ndim)

The dimension of array is:  3


#### Boolean Array

In [10]:
bool_array=np.array([True,False,False,True])
bool_array

array([ True, False, False,  True])

In [11]:
bool_array.dtype

dtype('bool')

#### Shape and size of an array

In [12]:
a=np.array([[1,2,3],
           [4,5,6]])
print("Shape of array: ",a.shape)


b=np.array([[1,2,3],
           [4,5,6]])
print("Size of array: ",b.size)

Shape of array:  (2, 3)
Size of array:  6


#### Conversion of NumPy Array

In [46]:
#np.arange(start,end,step size) generates numpy array such that the array include 'start' but 'stop' is exclusive. Step size is the difference between consecutive numbers in the array

a = np.arange(1, 12, 2)
print(a)
print(type(a))
print(a.shape)

[ 1  3  5  7  9 11]
<class 'numpy.ndarray'>
(6,)


#### Indexing in NumPy

In [14]:
a=np.array([[1,2,3],
           [4,5,6]])
a[(1,2)] #first value is row and second is column. this way we can get a particular element

np.int64(6)

In [15]:
#in case of rank 3 numpy array
b= np.array([[[10,20],[30,40]],
             [[40,50],[60,70]],
             [[80,90],[100,110]]])
b[(1,0,1)]

np.int64(50)

#### Slicing in NumPy

In [16]:
#Slicing in NumPy arrays is similar to slicing in Python lists, but with additional capabilities for multi-dimensional arrays.
#for 1d array
arr=np.array([4,5,6,7,8])

In [17]:
arr[2:5] #array_name[inclusive:exclusive]

array([6, 7, 8])

In [19]:
arr[1:5:2] #slicing with steps

array([5, 7])

In [19]:
#for 2d array
arr2d = np.array([[0, 1, 2], 
                  [3, 4, 5], 
                  [6, 7, 8], 
                  [9, 10, 11]])

In [22]:
print(arr2d[1:3,:])

[[3 4 5]
 [6 7 8]]


In [30]:
#to slice specific rows and columns
arr2d[1, :]

array([3, 4, 5])

In [24]:
arr2d[:, 1]

array([ 1,  4,  7, 10])

#### Data types in numpy

In [31]:
a=np.array([1,2])
print('The datatype is:',a.dtype)

The datatype is: int64


In [32]:
# in case of float values
b=np.array([1.0,2.0])
print('The datatype is:',b.dtype)

The datatype is: float64


In [26]:
# int64 represents 64-bit signed integer
# float64 represents double precision float

In [27]:
c=np.array([1,2],dtype=np.float64)
c.dtype

dtype('float64')

In [28]:
c

array([1., 2.])

#### Arange

In [47]:
# similar to 'range' function, but it returns a NumPy array instead of a list.
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#specifying start,stop and step
b=np.arange(0,12,2)
b
#here start value is inclusive and stop value is exclusive.

array([ 0,  2,  4,  6,  8, 10])

#### Sorting Numpy Array

In [31]:
arr=np.array([5,6,2,3,8,7])
np.sort(arr)

array([2, 3, 5, 6, 7, 8])

In [32]:
#sorting in descending order
np.sort(arr)[::-1]
#[::-1] is a slice notation used to reverse the sorted array obtained from the above code
#change the value after :: to provide the steps

array([8, 7, 6, 5, 3, 2])

#### Deleting elements from Numpy Array

In [34]:
new_arr=np.array([1,2,3,4,5])
new_arr

array([1, 2, 3, 4, 5])

In [37]:
np.delete(new_arr,3) # 3 is an index

array([1, 2, 3, 5])

In [38]:
array = np.array([[1, 2, 3, 4, 5],
                  [10,20,30,40,50],
                  [11,22,33,44,55]])
np.delete(array, 1, axis=1)
#np.delete(array, 1,axis = 1) is used for deleting elements at index 1 along axis 1 (columns).

array([[ 1,  3,  4,  5],
       [10, 30, 40, 50],
       [11, 33, 44, 55]])

#### Searching in NumPy

##### np.where

In [39]:
a=np.array([10,20,30,40,50])

In [40]:
index =np.where(a == 30)
index #This is a tuple with one element. That single element is a NumPy array.

(array([2]),)

In [41]:
#accessing the element in the array which is inside the tuple
index[0]

array([2])

In [39]:
index[0].dtype

dtype('int64')

### Numpy Array vs Python List

In [40]:
#At first glance, NumPy arrays are similar to Python lists. They both serve as containers with fast item getting and setting and somewhat slower inserts and removals of elements.The hands-down simplest example when NumPy arrays beat lists is arithmetic:
#for example squarring each number in a list and an array
a=[1,2,3]
[i*2 for i in a]

[2, 4, 6]

In [42]:
#using numpy
b=np.array([1,2,3])
b*2

array([2, 4, 6])

In [48]:
#similarly for adding two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [49]:
#python list
a=[1,2,3]
b=a #no copy
c=a[:] # copy
d=a.copy() #copy

In [50]:
#numpy array
a=np.array([1,2,3])
b=a #no copy
c=a[:] #no copy
d=a.copy() #copy

### Statistical Operations

#### Mean

In [45]:
array1 = np.random.randint(0,10,5)
array1

array([9, 0, 6, 4, 0])

In [46]:
np.mean(array1)

3.8

#### Median

In [47]:
array2=np.random.randint(0,10,5)
np.median(array2)

4.0

#### Standard Deviation

In [48]:
array3=np.random.randint(0,10,5)
np.std(array3)

1.9390719429665317

### Finding Min, Max and Sum

In [49]:
arr=np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

#### Min

In [50]:
np.min(arr)

5

#### Max

In [51]:
np.max(arr)

25

#### Sum

In [52]:
np.sum(arr)

75

### Broadcasting in NumPy

#### Broadcasting is a process in which NumPy automatically expands the smaller array to match the shape of the larger array during arithmetic operations.

In [53]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
b=np.arange(5).reshape((5,1))#reshape function as the name suggests, is used to reshape the array
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [55]:
a+b

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

##### Here, 'a' and 'b' arrays are expanded to a common shape, which in this case is (5,5). In 'a' the row is duplicated and expanded to make 5 rows and in 'b' the column is duplicated and expanded to make 5 columns.